name: Automatic Tests

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qt6-base-dev-tools libqt6serialport6-dev qt6-base-dev libqt6svg6-dev libqt5serialport5-dev libgtest-dev build-essential cmake libsqlite3-dev qt6-base-dev libgl1-mesa-dev libegl1-mesa-dev cmake

    - name: Initialize submodules
      run: git submodule update --init --recursive


    - name: Configure and build project
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build 
        export QT_QPA_PLATFORM=offscreen
        make check

    - name: Debug README.md contents
      run: cat README.md
